language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=latest
        - TEST_COVERAGE=true

    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=latest

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update $COMPOSER_ARGS --prefer-lowest --prefer-stable ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS ; fi
  - stty cols 120 && composer show

script:
  - composer run-script ci
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer run-script ci-coverage ; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then chmod +x php-coveralls.phar ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php php-coveralls.phar -v -x build/coverage/clover.xml -o ./build/coveralls.json ; fi

notifications:
  email: false
